#!/bin/bash
# docker wordpress needs 4 things to work:
# Database name
# Database username: jtian
# Database password: (MD5)abc123
# Database server

docker run --name lair --network jtian-net -p 8080:80 -e WORDPRESS_DB_HOST=spawning-pool -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_NAME=zerglings -e WORDPRESS_DB_PASSWORD=Kerrigan -d wordpress